### ISSUE TITLE
Fix usage of mail command on Linux

### ISSUE THREAD

**Issue by smu** [zertrin/duplicity-backup#81] opened 2015-01-20 12:47 UTC
When using ```MAIL="mail"``` on a Linux system (tested with Debian wheezy) the command parameters should be the same as for ```FreeBSD|Darwin|DragonFly|OpenBSD```.
For instance, ```-f ${EMAIL_FROM}``` is not an option in Debian wheezy and results in an additional email send to ```-f@domain```

**Comment by smu** [comment] 2015-01-20 12:58
Pull request is in issue #82. I could not find an easy way to attach a pull request to this issue.

**Comment by zertrin** [comment] 2015-01-20 17:47
As in the issue #80, could you provide the output of the following command (note the difference, here we test the `mail` command):

    dpkg -S $(readlink -e $(which mail))

On my systems (debian wheezy and jessie) I have the following output:

    bsd-mailx: /usr/bin/bsd-mailx

**Comment by smu** [comment] 2015-01-20 19:09
Same output as for mailx:

% dpkg -S $(readlink -e $(which mail))
bsd-mailx: /usr/bin/bsd-mailx

**Comment by phillxnet** [comment] 2015-01-20 19:20
In case it helps on my Ubuntu 14.04.1 I have:-
dpkg -S $(readlink -e $(which mail))
mailutils: /usr/bin/mail.mailutils
&
dpkg -S $(readlink -e $(which mailx))
mailutils: /usr/bin/mail.mailutils
ie:-
/usr/bin/mail -> /etc/alternatives/mail
/usr/bin/mailx -> /etc/alternatives/mailx
/etc/alternatives/mail -> /usr/bin/mail.mailutils
/etc/alternatives/mailx -> /usr/bin/mail.mailutils

**Comment by smu** [comment] 2015-01-20 19:29
The following command is executed when ```MAIL="mail"```

```/usr/bin/mail -s 'dub tests' MAILFROM MAILTO -- -f MAILFROM```

And mail interprets this in the way that it sends the mail to MAILFROM, MAILTO, and '-f'.

**Comment by zertrin** [comment] 2015-01-23 19:44
Thanks for the informations!

As for the issue #80 I'll try to test it properly soon.

**Comment by martinpeck** [comment] 2015-11-03 09:03
Hi there. Is there any update on this issue? I'm using ubuntu and have the same issue (that the -f@domain user is on the TO line, and the FROM is not as intended).

**Comment by zertrin** [comment] 2016-04-01 21:36
Once again thanks for reporting the issue and sorry for the very long delay before being able to investigate further.

I finally rewrote the entire email sending section of the script (see pull request #120), thus I'm closing this issue which is based on the old version of the code.

I welcome any feedback, feel free to test and open a new issue if any problem arise with the rework.

**Closed by zertrin** 2016-04-01 21:36 UTC
Labels: not-sure-if-bug-or-not
