### ISSUE TITLE
syntax error on line 314 breaks script

### ISSUE THREAD

**Issue by michaelbriordan** [zertrin/duplicity-backup#186] opened 2018-12-26 22:19 UTC
The following error occurs when I try to run the script (CentOS 7):

```
duplicity-backup.sh: line 314: syntax error near unexpected token `>'
duplicity-backup.sh: line 314: `exec 2> >(tee -ia "${LOGFILE}" >&2)'
```

**Comment by zertrin** [comment] 2020-01-21 06:44
Sorry, I am not actively maintaining the script any more, and I never used CentOS either. I don't know what the issue is.

I'll update the project soon to reflect the fact that it is not maintained. In the meantime I'll close this. Feel free to comment here if you have found a solution for your problem.

**Closed as completed** 2020-01-21 06:44 UTC
Labels: bug
